package corba.camara;


/**
* corba/camara/suscripcionD.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ubuntu_sdi/SDI/ws/TFinal_agencia-robots-Corba/robot.idl
* domingo 10 de enero de 2016 12H29' CET
*/

public final class suscripcionD implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public corba.camara.IPYPortD iport = null;
  public corba.khepera.escenario.EscenarioD esc = null;

  public suscripcionD ()
  {
  } // ctor

  public suscripcionD (int _id, corba.camara.IPYPortD _iport, corba.khepera.escenario.EscenarioD _esc)
  {
    id = _id;
    iport = _iport;
    esc = _esc;
  } // ctor

} // class suscripcionD
