package corba.robot;


/**
* corba/robot/RobotSeguidorIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ubuntu_sdi/SDI/ws/PR04_prj-difusion/src/robot.idl
* viernes 23 de octubre de 2015 09H11' CEST
*/

public interface RobotSeguidorIntOperations 
{
  void ObtenerEstado (corba.instantanea.EstadoRobotDHolder est);
} // interface RobotSeguidorIntOperations
