package corba.robot;


/**
* corba/robot/RobotSeguidorInt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Smiley/Dropbox/workspaceCOCO/prj-corba/robot.idl
* lunes 16 de noviembre de 2015 12H41' CET
*/

public interface RobotSeguidorInt extends RobotSeguidorIntOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RobotSeguidorInt
