package corba.camara;


/**
* corba/camara/CamaraIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Smiley/Dropbox/workspaceCOCO/prj-corba/robot.idl
* lunes 16 de noviembre de 2015 12H41' CET
*/

public interface CamaraIntOperations 
{
  corba.camara.suscripcionD SuscribirRobot (String IORrob);
} // interface CamaraIntOperations
