package corba.camara;

/**
* corba/camara/IPYPortDHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Smiley/Dropbox/workspaceCOCO/prj-corba/robot.idl
* lunes 16 de noviembre de 2015 12H41' CET
*/

public final class IPYPortDHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.camara.IPYPortD value = null;

  public IPYPortDHolder ()
  {
  }

  public IPYPortDHolder (corba.camara.IPYPortD initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.camara.IPYPortDHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.camara.IPYPortDHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.camara.IPYPortDHelper.type ();
  }

}
