package corba.camara;


/**
* corba/camara/IPYPortD.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ubuntu_sdi/SDI/ws/PR04_prj-difusion/src/robot.idl
* viernes 23 de octubre de 2015 09H11' CEST
*/

public final class IPYPortD implements org.omg.CORBA.portable.IDLEntity
{
  public String ip = null;
  public int port = (int)0;

  public IPYPortD ()
  {
  } // ctor

  public IPYPortD (String _ip, int _port)
  {
    ip = _ip;
    port = _port;
  } // ctor

} // class IPYPortD
