package corba.camara;


/**
* corba/camara/suscripcionD.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Smiley/Dropbox/workspaceCOCO/prj-corba/robot.idl
* lunes 16 de noviembre de 2015 12H41' CET
*/

public final class suscripcionD implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public corba.camara.IPYPortD iport = null;

  public suscripcionD ()
  {
  } // ctor

  public suscripcionD (int _id, corba.camara.IPYPortD _iport)
  {
    id = _id;
    iport = _iport;
  } // ctor

} // class suscripcionD
