package corba.robot;


/**
* corba/robot/RobotSeguidorIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ubuntu_sdi/SDI/ws/TRFinal_agencia-robots-Corba/robot.idl
* domingo 10 de enero de 2016 12H16' CET
*/

public interface RobotSeguidorIntOperations 
{
  void ObtenerEstado (corba.instantanea.EstadoRobotDHolder est);
  void ModificarEscenario (corba.khepera.escenario.EscenarioD esc);

  // raises (CORBA::COMM_FAILURE);
  void ModificarObjetivo (corba.khepera.robot.PosicionD NuevoObj);
  void ModificarPosicion (corba.khepera.robot.PosicionD npos);
  void ModificarLider (int idLider);
} // interface RobotSeguidorIntOperations
