package corba.camara;


/**
* corba/camara/IPYPortD.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ubuntu_sdi/SDI/ws/TRFinal_agencia-robots-Corba/robot.idl
* domingo 10 de enero de 2016 12H16' CET
*/

public final class IPYPortD implements org.omg.CORBA.portable.IDLEntity
{
  public String ip = null;
  public int port = (int)0;

  public IPYPortD ()
  {
  } // ctor

  public IPYPortD (String _ip, int _port)
  {
    ip = _ip;
    port = _port;
  } // ctor

} // class IPYPortD
