package corba;


/**
* corba/EchoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ubuntu_sdi/SDI/ws/PR03_prj-corba/src/Echo.idl
* martes 13 de octubre de 2015 13H13' CEST
*/

public interface EchoOperations 
{
  String Echo (String input);
} // interface EchoOperations
