package corba.consola;


/**
* corba/consola/ConsolaIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ubuntu_sdi/SDI/ws/TRFinal_agencia-robots_UDP/robot.idl
* domingo 10 de enero de 2016 11H04' CET
*/

public interface ConsolaIntOperations 
{
  void ModificarEscenario (corba.khepera.escenario.EscenarioD esc);
  boolean estoyviva ();
} // interface ConsolaIntOperations
