package corba.instantanea;


/**
* corba/instantanea/EstadoRobotD.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Smiley/Dropbox/workspaceCOCO/prj-corba/robot.idl
* lunes 16 de noviembre de 2015 12H41' CET
*/

public final class EstadoRobotD implements org.omg.CORBA.portable.IDLEntity
{
  public String nombre = null;
  public int id = (int)0;
  public String IORrob = null;

  public EstadoRobotD ()
  {
  } // ctor

  public EstadoRobotD (String _nombre, int _id, String _IORrob)
  {
    nombre = _nombre;
    id = _id;
    IORrob = _IORrob;
  } // ctor

} // class EstadoRobotD
