package corba.instantanea;


/**
* corba/instantanea/EstadoRobotD.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ubuntu_sdi/SDI/ws/PR04_prj-difusion/src/robot.idl
* viernes 23 de octubre de 2015 09H11' CEST
*/

public final class EstadoRobotD implements org.omg.CORBA.portable.IDLEntity
{
  public String nombre = null;
  public int id = (int)0;
  public String IORrob = null;

  public EstadoRobotD ()
  {
  } // ctor

  public EstadoRobotD (String _nombre, int _id, String _IORrob)
  {
    nombre = _nombre;
    id = _id;
    IORrob = _IORrob;
  } // ctor

} // class EstadoRobotD
