package corba.instantanea;


/**
* corba/instantanea/InstantaneaD.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /home/ubuntu_sdi/SDI/ws/PR04_prj-difusion/src/robot.idl
* viernes 23 de octubre de 2015 09H11' CEST
*/

public final class InstantaneaD implements org.omg.CORBA.portable.IDLEntity
{
  public corba.instantanea.EstadoRobotD estadorobs[] = null;

  public InstantaneaD ()
  {
  } // ctor

  public InstantaneaD (corba.instantanea.EstadoRobotD[] _estadorobs)
  {
    estadorobs = _estadorobs;
  } // ctor

} // class InstantaneaD
