package corba.instantanea;


/**
* corba/instantanea/InstantaneaD.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Smiley/Dropbox/workspaceCOCO/prj-corba/robot.idl
* lunes 16 de noviembre de 2015 12H41' CET
*/

public final class InstantaneaD implements org.omg.CORBA.portable.IDLEntity
{
  public corba.instantanea.EstadoRobotD estadorobs[] = null;

  public InstantaneaD ()
  {
  } // ctor

  public InstantaneaD (corba.instantanea.EstadoRobotD[] _estadorobs)
  {
    estadorobs = _estadorobs;
  } // ctor

} // class InstantaneaD
